### ISSUE TITLE
eloc & markdown-deck 首次使用反馈汇总

### ISSUE THREAD

**Issue by zthxxx** [amio/eloc#1]
Thanks for the great work!

以下是一些反馈

- 左侧编辑器功能太弱
  - 通过 <kbd>ESC</kbd> 每次打开编辑器不会自动跳转到当前页面对应源码位置
  - [建议] 编辑器和展示页面/route 应该同步滚动更新
  - 缺少编辑器高亮功能
  - 缺少自动缩进
  - [BUG] 有时编辑时 `enter` 后光标所在位置会被滚动到顶部 ([chromium#997266](https://bugs.chromium.org/p/chromium/issues/detail?id=997266))
  - edit 模式和 print 模式不能同时打开 (有时候预览全局样式需要)
  - 没有监听 markdown 文件变化

    所以不能直接编辑文件，只能通过浏览器编辑
  - 没有监听 include 目录变化，如果增加图片等，需要重新启动 eloc
  - [BUG] 缺少保存提示

    在 server 端关掉时保存会失败但没有提示

- [BUG] `script` tag 中的代码不会被执行 (`style` tag 能生效)
- 缺少支持全局 `style` / `script` tag 注入
- [BUG] 没有隔离单页面和全局 `style`

- [BUG] 特别大的 img 标签，没有自适应缩放到只有占满整个画布的大小
- [建议] 对于小图片可以在自适应时增加 medium-zoom 交互缩放

- [BUG] `eloc` include 参数解析使用 globs 时不应再做 split

- [建议] **约定**驱动默认的 md 文件名 (`eloc open` 能直接打开)
- [建议] **约定**会被 include 的默认的文件夹名 (如 `assets`)
- [BUG] **移动端** 手势捏合缩放会触发预期之外的翻页
- [建议] **移动端**点击屏幕等同于桌面端 <kdb>Space</kdb> 切换下一页
- [建议] 暴露可配置项并能从 `front-matter` 或者配置文件读取
  - [建议] 第一个 `---` 以上内容固定作为 `front-matter`
  - [建议] 配置项 title, description
  - [建议] 可配置自定义快捷键 

    (会与有些 chrome 插件快捷键冲突)
  - [建议] 可配置是否能点击空白处 (`body`) 翻页
  - [建议] 可配置是否展示当前播放进度 

    (类 mdx-deck 进度条)
  - [建议] 增加快捷键 (?) 以显示现有哪些快捷键
  - [建议] 增加快捷键以显示备注

**Comment by amio** [comment]
感谢~ 这几项可以确认：

Add

- [ ] 保持编辑器光标位置于当前页面切换同步
- [ ] 增加保存提示信息（以及失败的提示）
- [ ] 全局自定义样式（支持载入外部 css 文件）
- [ ] 局部自定义样式（inline `<style />`）
- [ ] 移动端点击切换下一页
- [ ] 进度指示（可能是 progress bar 吧）

Fix

- [ ] 图片自适应（应该修复了，确认下）
- [ ] `--include` 参数与 globs 语法保持一致

Maybe

- `SHIFT+?` 显示快捷键的帮助信息
- front matter 配置项

**Comment by amio** [comment]
编辑时 Enter 会触发诡异滚动的问题终于稳定重现了，我一度猜测会不会跟 shadow dom 有关，后来发现是 textarea 的锅：

https://bugs.chromium.org/p/chromium/issues/detail?id=997266&q=textarea%20enter&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

就坐等 Google 修复吧 ☕️

**Comment by zthxxx** [comment]
emmmm

Safari 12.1.1 未能复现回车键滚动问题，但也出现了打开编辑器没有自动滚动到当前页的问题

**Comment by amio** [comment]
@zthxxx markdown-deck 的 1.5.2 完善了下相关问题，eloc 还没更新依赖

**Comment by VoganWong** [comment]
我实现了简单的「进度指示」不知是不是你想要的 @zthxxx 
![progress-bar](https://user-images.githubusercontent.com/13285922/68102765-14332800-ff0f-11e9-91a8-dea56e59be30.gif)

**Comment by zthxxx** [comment]
@VoganWong  cool

**Comment by amio** [comment]
"移动端点击切换下一页" 暂时不想做了，未来有空再支持
其他功能都已实现，再修修 bug，准备发版 1.2 💃
