### ISSUE TITLE
how to use -css args?

### ISSUE THREAD

**Issue by sweetalin** [amio/eloc#253]
i try this cannot work
eloc presentation.md --css /Users/javaliu/html/background.css
please give me a   Detailed description  thanks！

target  is  to use  background picture  all the presentation

**Comment by sweetalin** [comment]
i try this
eloc presentation.md --css background.css
and css file is
body {
  background-color: lightblue;
}

h1 {
  color: blue;
  margin-left: 20px;
}

but the result is   only 
# markdown tag change a color ,and the backgroupd color cant  change

**Comment by sweetalin** [comment]
i try this
<style>
.slide {
  background: url(https://el-capitan.now.sh) center;
  background-size: cover;
}
.content { filter: invert() }
code { opacity: 0.8 }
</style>

copy this to  css  file  
and run .
then  all the page  have no view???  just  blank

**Comment by amio** [comment]
> eloc presentation.md --css background.css
@sweetalin you may need a higher priority for body selector:

```
body {
    background-color: lightblue !important;
}
```
